version: '3'

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - backend/.env
    command: >
      sh -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000 &&
      python manage.py createsuperuser"
    volumes:
      - media_volume:/backend/media
      - static_data:/backend/static
    expose:
      - 8000
    networks:
      - custom


  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - media_volume:/backend/media
      - static_data:/var/www/html/static
      - ./devops/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - custom


  telebot:
    container_name: telebot
    image: telebot
    restart: always
    build:
      context: .
      dockerfile: ./telebot/Dockerfile
    env_file:
      - telebot/.env
    expose:
      - 6000
    depends_on:
      - backend
      - web
    networks:
      - custom


networks:
  custom:
    driver: bridge

volumes:
  media_volume:
  static_data:
